### ISSUE TITLE
Support for sharding layer

### ISSUE THREAD

**Issue by miguelcnf** [influxdata/influxdb-relay#10]
Hi folks, more of a question for clarification and not so much an issue.

I don't think the README is clear on wether the relay supports (or is planned to support) acting as the sharding layer mentioned.

**Comment by miguelcnf** [comment]
Just looking at the code I think I can answer my own question and say that it doesn't support it at the moment, but the question about the planned support still stands. I think the README might be a bit misleading if that's not the case.

**Comment by joelegasse** [comment]
@miguelcnf Sorry for the delay. I'll add a note to the sharding section that `influxdb-relay` will not implement this layer.
