### ISSUE TITLE
how to do query in relay?

### ISSUE THREAD

**Issue by zhiwzhao** [influxdata/influxdb-relay#11]
any body use query in relay?
i setup two relay, 
relay1[http:9096] relay2[http:9096]
when i write point, everything works fine,
but when i query, seems with port 9096 doesnot work? so how to query in the load balance?

thanks
Vita

**Comment by shanab** [comment]
I don't think relay is supposed to be used to do queries other than write queries. If you take a look at the [diagram](https://github.com/influxdata/influxdb-relay#description) in the readme, you can see that `/query` goes right to the InfluxDB box and not the relay box.

**Comment by gunnaraasen** [comment]
Yup, @shanab is correct. Relay is only meant to be used on the write path. The load balancer should send queries directly to the InfluxDB instances.

Relay may support some query handling in the future, but no work is planned at the moment.

**Comment by zhiwzhao** [comment]
@shanab @gunnaraasen you are may right. now i am looking for a whole solution with high availability.
currently, there is only influxdb-relay which implement write. how to build the load balancer? is there any guidance?

**Comment by gunnaraasen** [comment]
@zhiwzhao I opened up a new issue to track docs around setting up a load balancer for Relay. See https://github.com/influxdata/influxdb-relay/issues/14
