### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by danyli78** [influxdata/influxdb-relay#12]
go install github.com/influxdata/influxdb-relay
work/src/github.com/influxdata/influxdb-relay/relay/http.go:16:2: cannot find package "github.com/influxdata/influxdb/models" in any of:
       /usr/local/go/src/github.com/influxdata/influxdb/models (from $GOROOT)
       /root/work/src/github.com/influxdata/influxdb/models (from $GOPATH)
work/src/github.com/influxdata/influxdb-relay/relay/config.go:6:2: cannot find package "github.com/naoina/toml" in any of:
       /usr/local/go/src/github.com/naoina/toml (from $GOROOT)
       /root/work/src/github.com/naoina/toml (from $GOPATH) (edited)

new messages

**Comment by zhiwzhao** [comment]
before you use "go install",  please use "go get" to download the code.

**Comment by danyli78** [comment]
thanks it works
