### ISSUE TITLE
how to implement in Load balancer for recovery?

### ISSUE THREAD

**Issue by zhiwzhao** [influxdata/influxdb-relay#20]
in Recovery part, there is step -- "Tell the load balancer to stop sending query traffic to the server that was down".
now i am already setup all of components with **nginx**, but how to implement this step?

any body can give me help? many thanks!

**Comment by joelegasse** [comment]
One way would be to update the config file for nginx, and then issue a `nginx -s reload` to reload the config with the old backend removed/disabled.

This falls under the category of "operator intervention required", and is not directly related to the relay.

Hopefully what I said will get you started in the right direction. If you need any further help with nginx, there are definitely better places to ask than here. :-)

**Comment by zhiwzhao** [comment]
@joelegasse is it possible to do health check in nginx for the server node,,nginx check some port in node and then know if server works or not?

**Comment by sLuvpreet33** [comment]
Do influxdb-relay works if we only have 1 influxbd server ?

Because that 1 server sometimes go down, and results in data loss.

**Comment by sibis** [comment]
@luvpreetsingh I think your assumption about High Availability(HA) is totally wrong, Influx-relay is only for HA setup where you have 2 influx servers running on different machines(obvi different IPs) and you send the data to influx-relay, It takes care of inserting to both the servers.

One drawback is it wont handle the failover case, If any one influx server goes down and comes up after sometime it wont have the data in downtime interval. Hope you got it.
