### ISSUE TITLE
Unable to install and run Influxdb-relay

### ISSUE THREAD

**Issue by sagarmah** [influxdata/influxdb-relay#27]
I am following all instructions in the readme.md, yet it fails at the very first step at
$ go install github.com/influxdata/influxdb-relay
Error:
can't load package: package github.com/influxdata/influxdb-relay: no buildable Go source files.

I even tried cloning the code in the directory and tried running build.py
it gives error saying could not find dependencies; go
I have installed go properly on my system. I am sure there is no issue on your part, but I am fairly new to both influxdb-relay as well as Go. Also if someone can dockerize the relay, it will be great help.
Thanks

**Comment by sagarmah** [comment]
I am having the same issue as issue#12, but even when I do a go get ...
it gives Error:
can't load package: package github.com/influxdata/influxdb-relay: no buildable Go source files in /home/sagar/influxdbrelay/go/src/github.com/influxdata/influxdb-relay

**Comment by joelegasse** [comment]
Sorry, the command should be `go get -u github.com/influxdata/influxdb-relay`

I'll update the docs to include that.

**Comment by joelegasse** [comment]
If you are still getting that error, you might need to remove the `influxdb-relay` directory from your current `GOPATH`

**Comment by sagarmah** [comment]
Hello,
Thanks for the update of the readme.md. I am still having issues, 
When I run $ go get -u github.com/influxdata/influxdb-relay
Error:
package github.com/influxdata/influxdb-relay: directory "/usr/local/go/src/github.com/influxdata/influxdb-relay" is not using a known version control system

So I removed the directory influxdb-relay and tried again and got,
package github.com/influxdata/influxdb-relay: cannot download, $GOPATH not set. For more details see: go help gopath
I have the right gopath as we can see in the ~/.profile
`# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
export PATH=$PATH:/usr/local/go/bin
`
still gives gopath not set error.
Can you please help me out, also is there a reliable ready image on dockerhub for the influxdb-relay?
