### ISSUE TITLE
Error parsing packet in relay : unable to parse

### ISSUE THREAD

**Issue by smeapng** [influxdata/influxdb-relay#29]
Hello,

I am sanding them metric since collectd on UDP directly on the relay influxDB and I have this message when I run the relay:

<pre><code>
/usr/local/go/bin/influxdb-relay -config relay.toml 
2016/06/10 16:11:50 starting relays...
2016/06/10 16:11:50 Starting HTTP relay "example-http" on 127.0.0.1:9096
2016/06/10 16:11:50 Starting UDP relay "influxdb-udp" on 0.0.0.0:25826
2016/06/10 16:11:50 Error parsing packet in relay "influxdb-udp" from 127.0.0.1:35398: unable to parse 'host1.local
                                                                                                                             ֲ����9	
                                                                                                                                        �interface	eth0if_octets
                                                                                                                                                                          ֲ����if_errors
�      eth1if_octetsy��+��                                                                                                                                                           ֲ��
                                  ֲ����]if_errors
                                                      ֲ�����	diskvdadisk_octets��)t
disk_opsZLm�                                                                             ֲ���	(
                ֲ����disk_time\��
                                        ֲ���ddisk_merged��
                                                                   ֲ�����
                                                                          memory
                                                                                  memory	used�\�A
buffered�5�A                                                                                     ֲ����6
              ֲ����4
                    cached���Asponge02l.btsys.local
                                                      ֲ�6��rinterface	eth0if_errors
                                                                                          ֲ�6��%	eth1if_octetsVƣ����"{
                                                                                                                                    ֲ�6��Fif_errors
                                                                                                                                                        ֲ�6�u]	diskvdadisk_octets���`	��~�
                                                                                                                                                                                                   ֲ�6��Wdisk_mergedN]<�)�
                           ֲ�6��Gdisk_time�z���
disk_ops.��W���                                ֲ�6�{F
                    ֲ�6�+�	load	load!q=': missing fields
unable to parse 'ףp�?ffffff�?��(\�?
                                  ֲ�6�!�
                                         memory
                                                memory	used.)�A
                                                                  ֲ�6���
                                                                        cached ��A
                                                                                    ֲ�6���	free N�A
buffered���A': invalid field format                                                                    ֲ�6�A
</pre></code>

Here is the configuration I have in the relay:

<pre><code>
[[http]]
name = "example-http"
bind-addr = "127.0.0.1:9096"
output = [
    { name="local1", location = "http://127.0.0.1:8086/write" },
    { name="local2", location = "http://127.0.0.1:7086/write" },
]

[[udp]]
name = "influxdb-udp"
bind-addr = "0.0.0.0:25826"
read-buffer = 0 # default
output = [
    { name="influxdb1", location="host1.local:25826", mtu=512 },
    { name="influxdb2", location="host2.local:25826", mtu=1024 },
]
</pre></code>

I have version 5.4 of collectd and 0.13 version of influxdb (although finally the metric does not arrive until the base ...)

Do you have an idea of why the relay can not parse the metric correctly sent by collectd?

Thank you.

Cordially.

**Comment by joelegasse** [comment]
The UDP endpoint for the relay only handles InfluxDB line protocol over UDP, similar to the `[[udp]]` service in InfluxDB (https://docs.influxdata.com/influxdb/v0.13/write_protocols/udp/).

The other inputs would be possible, and for the purposes of the relay, would ideally be implemented as a front-end input only, feeding the HTTP backend InfluxDB instances (to take advantage of the buffering logic). But for now, the relay only supports line protocol.
