### ISSUE TITLE
InfluxDB HA Subscriptions for Kapacitor

### ISSUE THREAD

**Issue by allen13** [influxdata/influxdb-relay#31]
I am currently integrating kapacitor into my alerting system and wanted to address HA concerns related to subscriptions. Currently the only way to reliably do this is to have a subscription on each InfluxdDB server, which unfortunately doubles data and alerts. InfluxDB relay is in a unique position where it could be in charge of distributing the subscriptions itself since that is what is it basically already doing with the multiple InfluxDB databases. 

With the new http kapacitor endpoints you can just treat kapacitors as just another InfluxDB database, which seems like the best solution so far.  Are there any other recommendations for official HA solutions for kapacitor?

**Comment by nathanielc** [comment]
> With the new http kapacitor endpoints you can just treat kapacitors as just another InfluxDB database, which seems like the best solution so far.

This is what we recommend. Disable subscriptions in Kapacitor and add it as a backend to the influxdb-relay. Here is an example conf https://github.com/influxdata/influxdb-relay/blob/master/kapacitor.toml

**Comment by forestjohnsonpeoplenet** [comment]
How can we configure capacitor to subscribe to nothing? The example config shows:

```
  [influxdb.excluded-subscriptions]
    # Set of databases and retention policies to exclude from the subscriptions.
    # If influxdb.subscriptions is empty it will subscribe to all
    # except databases listed here.
    #
    # Format
    # db_name = <list of retention policies>
    #
    # Example:
    # my_database = [ "default", "longterm" ]
```

Do I have to add a line for every database with every retention policy ?  What if I add a new database?
