### ISSUE TITLE
two influxdb node , The data is not synchronized

### ISSUE THREAD

**Issue by TUTUBIG** [influxdata/influxdb-relay#34]
I have two influxdb node :A,B,while A is down and B is up , I insert a data into the influxdb by influx-relay ,i can see this data in B ,then I set up A,but A has't this data ,what's wrong?

**Comment by gunnaraasen** [comment]
InfluxDB Relay is only meant to ensure there is a failover database available if one goes down. It does not provide data consistency.

To get consistent data between both nodes, you'll either need to query both nodes and merge the results, or overwrite the full shards from one node over the node that experienced downtime.

**Comment by sLuvpreet33** [comment]
Do influxdb-relay works if we only have 1 influxbd server ?

Because that 1 server sometimes go down, and results in data loss. Will it prevent data loss if I have 1 server ?
