### ISSUE TITLE
Unable to start relay with init.d

### ISSUE THREAD

**Issue by IwoTens** [influxdata/influxdb-relay#35]
I built a .deb file. After installing it, I tried to start the service, but I get the following error (inside the log file):

```
flag provided but not defined: -pidfile
Usage of influxdb-relay:
  -config string
        Configuration file to use
```

I tried to tinker around a bit, but didn't manage to get it to work properly.
This was on Ubuntu 14.04, so it is using init.d scripts.

**Comment by rossmcdonald** [comment]
This should now be resolved with #37, so you will need to rebuild the package with that fix. Let me know if you run into any further issues.
