### ISSUE TITLE
Add support for create database

### ISSUE THREAD

**Issue by nhaugo** [influxdata/influxdb-relay#48]

**Comment by Geospace** [comment]
Implemented in https://github.com/vente-privee/influxdb-relay/commit/a8e4974d7e40b90120acd43a42682cce6d6568e0

**Comment by Geospace** [comment]
@nhaugo Did you have the chance to try it ? We'll appreciate your feedback ! ;)

**Comment by timhallinflux** [comment]
The project is no longer active.
