### ISSUE TITLE
A question about the use of the relay with the collectd

### ISSUE THREAD

**Issue by gaoxiangsheng** [influxdata/influxdb-relay#54]
I’ve got some troubles in using influxdb-relay with the collectd. And I checked the udp.go, it seemed that it could not parse the data from collectd. 
Does the relay support listening for the writes from collectd and writing the data to each InfluxDB ?

**Comment by lin-credible** [comment]
** + 1 **

**Comment by nathanielc** [comment]
The relay only supports UDP writes in InfluxDB line protocol.

**Comment by sLuvpreet33** [comment]
Do influxdb-relay works if we only have 1 influxbd server ?

Because that 1 server sometimes go down, and results in data loss.

**Comment by hwy1782** [comment]
+1
