### ISSUE TITLE
Grafana is not working with relay

### ISSUE THREAD

**Issue by crazikPL** [influxdata/influxdb-relay#58]
I'm trying to setup influxdb-relay in my env, but stopped on problem with Grafana.
I've added new Datasource, with http://my.local.ip:9086/, but got an error:

> InfluxDB Error Response: invalid write endpoint

My current relay.toml:
```
[[http]]
name = "influxdb-http"
bind-addr = ":9086"
output = [
    { name = "influxdb_a", location = "http://my.local.ip:8086/write" },

]

[[udp]]
name = "influxdb-udp"
bind-addr = ":9086"
read-buffer = 0 # default
output = [
    { name = "influxdb_a", location = "my.local.ip:8086", mtu = 512 },

]
```

I'm using docker images: `appcelerator/influxdb-relay`, `influxdb:1.2.4` and `grafana:4.1.2`

**Comment by sofixa** [comment]
You can't use InfluxDB for reads, only writes, so you'll have to point Grafana directly to your InfluxDB server.

**Comment by crazikPL** [comment]
Oh, I see. Thank you! :)
