### ISSUE TITLE
Maintained fork by Vente-Privée

### ISSUE THREAD

**Issue by rockyluke** [influxdata/influxdb-relay#67]
Hello,

First of all thank you InfluxData & contributors for providing us such great tools. You've done an Amazing work.

We are very happy user of InfluxDB Relay at Vente-Privée but I seem that it's not maintained anymore (last commit is a bit old) and I respectfully understand that choice. That's why we plan to maintain it on https://github.com/vente-privee/influxdb-relay/tree/develop. The first main feature we want to add is **handle prometheus remote_write case**.

What we already have done:

* Add basic tests with golint & pylint
* Add CHANGELOG (sorry we start with our fork, we'll work on that)
* Add CONTRIBUTING guide
* Merge https://github.com/influxdata/influxdb-relay/pull/65
* Merge https://github.com/influxdata/influxdb-relay/pull/52
* Merge https://github.com/influxdata/influxdb-relay/pull/59
* Merge https://github.com/influxdata/influxdb-relay/pull/43
* Merge https://github.com/influxdata/influxdb-relay/pull/57

Feel free to join & help us by making more & more issues / PR 😄 

=> https://github.com/vente-privee/influxdb-relay

**Comment by knope** [comment]
have you been able to successfully remote_write to the relay endpoint using the native prom/  influx api?  if so can you update the Array of InfluxDB instances to use as backends for Relay in readme?


i'm still receiving ```server returned HTTP status 404 Not Found: {\"error\":\"invalid write endpoint\"} ```  when compiled and using the expected pattern ``` remote_write:
  - url: "<http://url>:7076/api/v1/prom/write?db=prometheus"
remote_read:
  - url: "<http://url>:7076/api/v1/prom/read?db=prometheus" ```

**Comment by rockyluke** [comment]
It's almost done on our side. It's working but more like quick and dirty hack. We plan to release it soon.

**Comment by rockyluke** [comment]
We just release it on the develop branch => https://github.com/vente-privee/influxdb-relay.

We've done performance test with Vegeta and we didn't see any differences.

Can you try it ?
