### ISSUE TITLE
Support for InfluxDB 2.0 API

### ISSUE THREAD

**Issue by mjiderhamn** [influxdata/influxdb-relay#81]
Please add support for relaying InfluxDB 2.0 API endpoints

**Comment by wemod123** [comment]
Any updates?

**Comment by dipeshtripathi** [comment]
This would be great! We are planning to upgrade from 1.8 to 2.0. The only thing stopping us right now is that there is no support in relay for 2.0. @jsternberg

**Comment by timhallinflux** [comment]
this project is effectively no longer being maintained.
