### ISSUE TITLE
HA influx on relay method

### ISSUE THREAD

**Issue by mohan-nagandlla** [influxdata/influxdb-relay#82]
HI team,
Its very pleasure to have the HA in influx i am new to this DB deployment, I have deployed the influx and connect the Prometheus to the influx every thing is good. Coming to the HA enable most of the documents are directing to use the relay method but i am not getting the clarity on that like who we are going to write the data with relay and do we check that and a few important aspects are need to know can you please guide me on that or is there any best documentation available on practical example (I read the documentation on official web set it is not clear)

**Comment by dipeshtripathi** [comment]
https://docs.openstack.org/developer/performance-docs/methodologies/monitoring/influxha.html#influxdbha-deployment-script

Give this a try.

**Comment by jhg03a** [comment]
That solution is slightly different than using the influxdb-relay.  Just adding a load balancer of some kind only issues a single write to an influxdb.  The influxdb-relay on the other hand forks the writes across all the member influxDB I think.

**Comment by dipeshtripathi** [comment]
No so we are adding the load balancer for redundancy between the relays.

The relay would still perform as intended.

**Comment by jhg03a** [comment]
Ah my mistake, I misunderstood the topology.
